openapi: 3.0.0
info:
  title: UsagiBooru API
  version: '2.0'
  contact:
    name: Omado
    url: https://twitter.com/shallow_omado
    email: dsgamer777@gmail.com
  description: 関連API
  license:
    name: AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.ja.html
servers:
- url: https://api.gochiusa.team
  description: Prod
- url: https://api-next.gochiusa.team
  description: Staging
- url: http://127.0.0.1:8080
  description: Dev
paths: {}
components:
  schemas: {}
  parameters: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
security:
  - Authorization: []