components:
  parameters:
    SearchQueryMylistAllow:
      description: マイリスト追加済みかを取得する0/1 (デフォルト1)
      in: query
      name: with_mylisted
      required: false
      schema:
        default: 1
        enum:
        - 1
        - 0
        example: 1
        format: int32
        maximum: 1
        minimum: 0
        type: integer
    SearchQueryMylistDeny:
      description: マイリスト追加済みかを取得する0/1 (デフォルト0)
      in: query
      name: with_mylisted
      schema:
        default: 0
        enum:
        - 0
        - 1
        example: 0
        maximum: 1
        minimum: 0
        type: integer
    SearchQueryOrder:
      description: ソート方向 d:降順(大→小) a:昇順(小→大)
      in: query
      name: order
      required: false
      schema:
        default: d
        enum:
        - d
        - a
        example: d
        maxLength: 1
        minLength: 1
        type: string
    SearchQueryPage:
      description: 'ページ番号 (NOTE: 1ページ辺りの応答は20件)'
      in: query
      name: page
      required: false
      schema:
        minimum: 1
        type: integer
    SearchQueryPerPage:
      description: 1ページ辺りの要素数
      in: query
      name: per_page
      required: false
      schema:
        default: 20
        enum:
        - 20
        - 40
        - 60
        - 80
        - 100
        example: 20
        maximum: 100
        minimum: 20
        type: integer
    SearchQuerySort:
      description: ソート方法 l:いいね数順 d:投稿日順
      in: query
      name: sort
      required: false
      schema:
        default: d
        enum:
        - l
        - d
        example: d
        type: string
    SearchQuerySortCatalog:
      description: ソート方法 c:ヒット数 d:最終更新 l:いいね数 n:名前
      in: query
      name: sort
      schema:
        default: d
        enum:
        - c
        - d
        - l
        - n
        example: d
        type: string
  schemas:
    ActivityPubActorStruct:
      description: 'ActivityPubのアクター(ユーザー)構造体(仮)

        https://argrath.github.io/activitypub/#actor-objects'
      properties:
        '@context':
          items:
            properties:
              '1':
                properties:
                  '@language':
                    minLength: 1
                    type: string
                required:
                - '@language'
                type: object
            type: object
          type: array
        followers:
          minLength: 1
          type: string
        following:
          minLength: 1
          type: string
        icon:
          items:
            type: string
          type: array
        id:
          minLength: 1
          type: string
        inbox:
          minLength: 1
          type: string
        liked:
          minLength: 1
          type: string
        name:
          minLength: 1
          type: string
        outbox:
          minLength: 1
          type: string
        preferredUsername:
          minLength: 1
          type: string
        summary:
          minLength: 1
          type: string
        type:
          minLength: 1
          type: string
      required:
      - type
      - id
      - inbox
      - outbox
      - preferredUsername
      - name
      - summary
      - icon
      title: ActivityPubActorStruct
      type: object
      x-examples:
        example-1:
          '@context':
          - https://www.w3.org/ns/activitystreams
          - '@language': ja
          followers: https://kenzoishii.example.com/followers.json
          following: https://kenzoishii.example.com/following.json
          icon:
          - https://kenzoishii.example.com/image/165987aklre4
          id: https://kenzoishii.example.com/
          inbox: https://kenzoishii.example.com/inbox.json
          liked: https://kenzoishii.example.com/liked.json
          name: 石井健蔵
          outbox: https://kenzoishii.example.com/feed.json
          preferredUsername: kenzoishii
          summary: この方はただの例です
          type: Person
    GeneralMessageResponse:
      description: 共通の応答構造体(404/401/400等を返す際に使用)
      properties:
        message:
          description: 応答メッセージ(何が間違っているかの詳細)
          minLength: 1
          type: string
      required:
      - message
      title: GeneralMessageResponse
      type: object
      x-examples:
        bad-request:
          message: Your request body is wrong.
        locked:
          message: Specified content is referenced from other content.
        no-permission:
          message: You don't have enough permission to do it.
        not-found:
          message: Specified content was not found.
    GetActivityPubGeneralResponse:
      description: ActivityPubのBoxを取得した際等に返される汎用応答構造体
      properties:
        '@context':
          minLength: 1
          type: string
        orderedItems:
          items:
            properties:
              name:
                minLength: 1
                type: string
              type:
                minLength: 1
                type: string
            required:
            - type
            - name
          minItems: 1
          type: array
          uniqueItems: true
        summary:
          minLength: 1
          type: string
        totalItems:
          type: number
        type:
          minLength: 1
          type: string
      required:
      - '@context'
      - summary
      - type
      - totalItems
      - orderedItems
      title: GetActivityPubGeneralResponse
      type: object
      x-examples:
        example:
          '@context': https://www.w3.org/ns/activitystreams
          orderedItems:
          - name: A Simple Note
            type: Note
          - name: Another Simple Note
            type: Note
          summary: Sally's notes
          totalItems: 2
          type: OrderedCollection
    PostActivityPubGeneralRequest:
      description: ActivityPubのBox宛へPOSTする場合の汎用要求構造体
      properties:
        '@context':
          minLength: 1
          type: string
        actor:
          properties:
            name:
              minLength: 1
              type: string
            type:
              minLength: 1
              type: string
          required:
          - type
          - name
          type: object
        object:
          properties:
            name:
              minLength: 1
              type: string
            type:
              minLength: 1
              type: string
          required:
          - type
          - name
          type: object
        summary:
          minLength: 1
          type: string
        type:
          minLength: 1
          type: string
      required:
      - '@context'
      - type
      - summary
      - actor
      - object
      title: PostActivityPubGeneralRequest
      type: object
      x-examples:
        example-1:
          '@context': https://www.w3.org/ns/activitystreams
          actor:
            name: Sally
            type: Person
          object:
            name: A Note
            type: Note
          summary: Sally did something to a note
          type: Activity
  securitySchemes:
    Authorization:
      scheme: bearer
      type: http
info:
  contact:
    email: dsgamer777@gmail.com
    name: Omado
    url: https://twitter.com/shallow_omado
  description: Activitypub related api (optional)
  license:
    name: AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.ja.html
  title: UsagiBooru Activitypub API
  version: '2.0'
openapi: 3.0.0
paths:
  /activitypub/artist/{artistID}:
    get:
      description: 'ActivityPubのユーザー情報(絵師)を返す

        (実際使うときは https://example.com/artist/{displayID} からリダイレクト?)'
      operationId: getActivityPubArtistActor
      responses:
        '200':
          content:
            application/activity+json:
              schema:
                $ref: '#/components/schemas/ActivityPubActorStruct'
          description: OK
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Not Found
      summary: Get activitypub artist actor
      tags:
      - activitypub
    parameters:
    - description: 対象の絵師ID
      in: path
      name: artistID
      required: true
      schema:
        type: integer
  /activitypub/artist/{artistID}/outbox:
    get:
      description: 他のサーバーがこのユーザーのメッセージを受け取るときにGETされる
      operationId: getActivityPubArtistOutbox
      responses:
        '200':
          content:
            application/activity+json:
              schema:
                $ref: '#/components/schemas/GetActivityPubGeneralResponse'
          description: OK
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Not Found
      summary: Provide federation artist message
      tags:
      - activitypub
    parameters:
    - description: 対象の絵師ID
      in: path
      name: artistID
      required: true
      schema:
        type: integer
  /activitypub/server:
    get:
      description: ActivityPubのユーザー情報(サーバー)を返す
      operationId: getActivityPubServerActor
      responses:
        '200':
          content:
            application/activity+json:
              schema:
                $ref: '#/components/schemas/ActivityPubActorStruct'
          description: OK
      summary: Get activitypub server base
      tags:
      - activitypub
  /activitypub/server/inbox:
    get:
      description: このサーバーが自分自身に来ている通知などを取得する際にGETされる
      operationId: getActivityPubServerInbox
      responses:
        '200':
          content:
            application/activity+json:
              schema:
                $ref: '#/components/schemas/GetActivityPubGeneralResponse'
          description: OK
      summary: Check federation server message
      tags:
      - activitypub
    post:
      description: 他のサーバーがこのサーバーに向けてメッセージを送るときにPOSTされる
      operationId: postActivityPubServerInbox
      requestBody:
        content:
          application/activity+json:
            schema:
              $ref: '#/components/schemas/PostActivityPubGeneralRequest'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Created
      summary: Recieve federation to server message
      tags:
      - activitypub
  /activitypub/server/outbox:
    get:
      description: 他のサーバーがこのサーバーのメッセージを受け取るときにGETされる
      operationId: getActivityPubServerOutbox
      responses:
        '200':
          content:
            application/activity+json:
              schema:
                $ref: '#/components/schemas/GetActivityPubGeneralResponse'
          description: OK
      summary: Provide federation server message
      tags:
      - activitypub
    post:
      description: このサーバーが他のサーバーに向けてメッセージを送るときにPOSTされる
      operationId: postActivityPubServerOutbox
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostActivityPubGeneralRequest'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Created
      summary: Send federation server message
      tags:
      - activitypub
  /activitypub/uploader/{accountID}:
    get:
      description: 'ActivityPubのユーザー情報(投稿者)を返す

        (実際使うときは https://example.com/uploader/{displayID} からリダイレクト?)'
      operationId: getActivityPubUploaderActor
      responses:
        '200':
          content:
            application/activity+json:
              schema:
                $ref: '#/components/schemas/ActivityPubActorStruct'
          description: OK
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Not Found
      summary: Get activitypub uploader actor
      tags:
      - activitypub
    parameters:
    - description: 対象のアカウントID
      in: path
      name: accountID
      required: true
      schema:
        type: string
  /activitypub/uploader/{accountID}/outbox:
    get:
      description: 他のサーバーがこのユーザーのメッセージを受け取るときにGETされる
      operationId: getActivityPubUploaderOutbox
      responses:
        '200':
          content:
            application/activity+json:
              schema:
                $ref: '#/components/schemas/GetActivityPubGeneralResponse'
          description: OK
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Not Found
      summary: Provide federation user message
      tags:
      - activitypub
    parameters:
    - description: 対象のアカウントID
      in: path
      name: accountID
      required: true
      schema:
        type: integer
security:
- Authorization: []
servers:
- description: Prod
  url: https://api.gochiusa.team
- description: Staging
  url: https://api-next.gochiusa.team
- description: Dev
  url: http://127.0.0.1:8080
tags:
- name: activitypub
