components:
  parameters:
    SearchQueryMylistAllow:
      description: マイリスト追加済みかを取得する0/1 (デフォルト1)
      in: query
      name: with_mylisted
      required: false
      schema:
        default: 1
        enum:
        - 1
        - 0
        example: 1
        format: int32
        maximum: 1
        minimum: 0
        type: integer
    SearchQueryMylistDeny:
      description: マイリスト追加済みかを取得する0/1 (デフォルト0)
      in: query
      name: with_mylisted
      schema:
        default: 0
        enum:
        - 0
        - 1
        example: 0
        maximum: 1
        minimum: 0
        type: integer
    SearchQueryOrder:
      description: ソート方向 d:降順(大→小) a:昇順(小→大)
      in: query
      name: order
      required: false
      schema:
        default: d
        enum:
        - d
        - a
        example: d
        maxLength: 1
        minLength: 1
        type: string
    SearchQueryPage:
      description: 'ページ番号 (NOTE: 1ページ辺りの応答は20件)'
      in: query
      name: page
      required: false
      schema:
        minimum: 1
        type: integer
    SearchQueryPerPage:
      description: 1ページ辺りの要素数
      in: query
      name: per_page
      required: false
      schema:
        default: 20
        enum:
        - 20
        - 40
        - 60
        - 80
        - 100
        example: 20
        maximum: 100
        minimum: 20
        type: integer
    SearchQuerySort:
      description: ソート方法 l:いいね数順 d:投稿日順
      in: query
      name: sort
      required: false
      schema:
        default: d
        enum:
        - l
        - d
        example: d
        type: string
    SearchQuerySortCatalog:
      description: ソート方法 c:ヒット数 d:最終更新 l:いいね数 n:名前
      in: query
      name: sort
      schema:
        default: d
        enum:
        - c
        - d
        - l
        - n
        example: d
        type: string
  schemas:
    GeneralMessageResponse:
      description: 共通の応答構造体(404/401/400等を返す際に使用)
      properties:
        message:
          description: 応答メッセージ(何が間違っているかの詳細)
          minLength: 1
          type: string
      required:
      - message
      title: GeneralMessageResponse
      type: object
      x-examples:
        bad-request:
          message: Your request body is wrong.
        locked:
          message: Specified content is referenced from other content.
        no-permission:
          message: You don't have enough permission to do it.
        not-found:
          message: Specified content was not found.
    GetNewsListResponse:
      description: ニュース情報一覧の応答構造体
      properties:
        news:
          items:
            $ref: '#/components/schemas/NewsStruct'
          type: array
      title: GetNewsListResponse
      type: object
      x-examples:
        example:
          news:
          - author:
              accountID: 1
              name: お窓
            body: This is next generation imageboard. This is challenge for me. I
              hope someone loves this project.
            color: 1
            date: '2021-03-22'
            newsID: 1
            title: Welcome to UsagiBooru!
    LightAccountStruct:
      description: アカウント情報の簡易構造体(読み取り専用)
      properties:
        accountID:
          description: アカウントID
          example: 1
          minimum: 1
          type: integer
        name:
          description: アカウント名
          example: お窓
          type: string
      title: LightAccountStruct
      type: object
      x-examples:
        example:
          accountID: 1
          name: お窓
    NewsStruct:
      description: サイト内ニュース情報の構造体
      properties:
        author:
          $ref: '#/components/schemas/LightAccountStruct'
        body:
          description: ニュース本文 3000文字まで
          example: This is next generation imageboard. This is challenge. I hope someone
            loves this project.
          maxLength: 3000
          minLength: 1
          type: string
        color:
          default: 1
          description: ニュース表記色(色はフロントエンドの実装次第)
          example: 1
          maximum: 9
          minimum: 1
          type: integer
        date:
          description: 投稿日付時刻
          example: '2021-03-22'
          format: date
          type: string
        newsID:
          description: ニュースID
          example: 1
          minimum: 1
          type: integer
        title:
          description: ニュースタイトル 50文字まで
          example: Welcome to UsagiBooru!
          maxLength: 50
          minLength: 1
          type: string
      title: NewsStruct
      type: object
      x-examples:
        example:
          author:
            accountID: 1
            name: お窓
          body: This is next generation imageboard. This is challenge. I hope someone
            loves this project.
          color: 1
          date: '2021-03-22'
          newsID: 1
          title: Welcome to UsagiBooru!
  securitySchemes:
    Authorization:
      scheme: bearer
      type: http
info:
  contact:
    email: dsgamer777@gmail.com
    name: Omado
    url: https://twitter.com/shallow_omado
  description: News related api (optional)
  license:
    name: AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.ja.html
  title: UsagiBooru News API
  version: '2.0'
openapi: 3.0.0
paths:
  /news:
    get:
      description: ニュース一覧を取得します
      operationId: getNewsList
      parameters:
      - $ref: '#/components/parameters/SearchQuerySort'
      - $ref: '#/components/parameters/SearchQueryOrder'
      - $ref: '#/components/parameters/SearchQueryPage'
      - $ref: '#/components/parameters/SearchQueryPerPage'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNewsListResponse'
          description: OK
      summary: Get all news
      tags:
      - news
    post:
      description: 'ニュースを追加します

        (管理者のみリクエストできます)'
      operationId: addNews
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsStruct'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsStruct'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Forbidden
      summary: Add news
      tags:
      - news
  /news/{newsID}:
    delete:
      description: '指定したニュースを削除します

        管理者のみリクエストできます'
      operationId: deleteNews
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: No Content
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Not Found
      summary: Delete news
      tags:
      - news
    get:
      description: 指定したニュースの内容を取得します
      operationId: getNews
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema:
                $ref: '#/components/schemas/NewsStruct'
          description: 応答のdataに返却されます
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Not Found
      summary: Get news
      tags:
      - news
    parameters:
    - description: 対象のニュースID
      in: path
      name: newsID
      required: true
      schema:
        exclusiveMinimum: true
        minimum: 1
        type: integer
    patch:
      description: '指定したニュースのタイトル/本文/カラーを編集します

        管理者のみリクエストできます'
      operationId: editNews
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsStruct'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsStruct'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralMessageResponse'
          description: Not Found
      summary: Edit news
      tags:
      - news
security:
- Authorization: []
servers:
- description: Prod
  url: https://api.gochiusa.team
- description: Staging
  url: https://api-next.gochiusa.team
- description: Dev
  url: http://127.0.0.1:8080
tags:
- name: news
